### ISSUE TITLE
import colab_utils.tboard failed

### ISSUE THREAD

**Issue by sergei3000** [mixuala/colab_utils#1]
Hi,

I tried the tensorboard script, but got an error saying: ModuleNotFoundError: No module named 'colab_utils'

**Comment by dmelladoc** [comment]
Did you clone this repo on your Colab VM?
You have to clone it first with ``!git clone <repository>`` and then you import this on your colab notebook.

**Comment by stenlytw** [comment]
Hi,

I also got the same error. Create` __init__.py` file solved the problem:
`!cat >colab_utils/__init__.py`

**Comment by acesaif** [comment]
So everytime I make a new `directory` and want to run `tensorboard`, I will have to `clone` this `repo`???

Even after `cloning` still the same issue...

**Comment by mixuala** [comment]
`__init__.py` added. So that's how modules work! 

you only have to import once.
