### ISSUE TITLE
Can I use tensorboard on local?

### ISSUE THREAD

**Issue by whitecoffee** [mixuala/colab_utils#2]
Thanks for your dedication, I have successfully run 'tensorboard' on VM.
The next question is can I copy the event file to google drive and download it to local machine ?

I have seen your code for 'GCS bucket', but it seems a little bit opaque to me.
Since I work on GCS only with a file called "tensorboard_x.ipynb".
I save my checkpoint and event file to ./tmp/mnist/ in VM.

Can you specifically point out the name of project and any other things in my case?

**Comment by mixuala** [comment]
`save_to_bucket()` copies both the latest `ckpt` plus all tensorboard event files as a tar file to the designated Google Cloud Storage bucket.

however, you can still find the tar file in `tar_filepath = os.path.join("/tmp", tar_filename)` if you want to download that to your local filesystem.


Here's a simple example for saving checkpoint and event files to GCS
```
def save_checkpoint_to_bucket( train_log, bucket=None, project=None, step=None, ):
  if step is None:
    step = get_step_from_latest_checkpoint(train_log)    
  bucket_path = colab_utils.gcloud.save_to_bucket(train_log, 
                                    bucket, 
                                    project, 
                                    step=step,
                                    save_events=True)
  return bucket_path


project_id = "my-project-id"
colab_utils.gcloud.gcloud_auth(project_id)
gcs_path = save_checkpoint_to_bucket( TBOARD_LOG )
print(gcs_path)



```

**Comment by whitecoffee** [comment]
WOW, thanks for your reply!!!!
