### ISSUE TITLE
OSError: [Errno 18] Invalid cross-device link: 'ngrok'

### ISSUE THREAD

**Issue by RossTntt** [mixuala/colab_utils#4]
code
```
import os
import colab_utils.tboard

# set paths
ROOT = os.getcwd()
LOG_DIR = os.path.join(ROOT, 'log')

# will install `ngrok`, if necessary
# will create `log_dir` if path does not exist
colab_utils.tboard.launch_tensorboard(bin_dir=ROOT, log_dir=LOG_DIR)

```

output

> calling wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip ...
> calling unzip ngrok-stable-linux-amd64.zip ...
>  
> OSError                                   Traceback (most recent call last)
> <ipython-input-29-8287c8a1eaf1> in <module>()
>       8 # will install `ngrok`, if necessary
>       9 # will create `log_dir` if path does not exist
> ---> 10 colab_utils.tboard.launch_tensorboard(bin_dir=ROOT, log_dir=LOG_DIR)
> 
> /content/drive/RoLab/transfer_learning_tutorial/colab_utils/tboard.py in launch_tensorboard(bin_dir, log_dir, retval)
>     111 
>     112   """
> --> 113   install_ngrok(bin_dir)
>     114 
>     115   if not tf.gfile.Exists(log_dir):  tf.gfile.MakeDirs(log_dir)
> 
> /content/drive/RoLab/transfer_learning_tutorial/colab_utils/tboard.py in install_ngrok(bin_dir)
>      79       print("calling unzip ngrok-stable-linux-amd64.zip ...")
>      80       get_ipython().system_raw( "unzip ngrok-stable-linux-amd64.zip" )
> ---> 81       os.rename("ngrok", "{}/ngrok".format(TARGET_DIR))
>      82       os.remove("ngrok-stable-linux-amd64.zip")
>      83       is_grok_avail = os.path.isfile(os.path.join(TARGET_DIR,'ngrok'))
> 
> OSError: [Errno 18] Invalid cross-device link: 'ngrok' -> '/content/drive/RoLab/transfer_learning_tutorial/ngrok'

**Comment by RossTntt** [comment]
should have a fold named ngrok before run code follow

**Comment by RossTntt** [comment]
should have a fold named ngrok before run code follow

**Comment by mixuala** [comment]
see: https://stackoverflow.com/questions/42392600/oserror-errno-18-invalid-cross-device-link
`os.rename only works if source and destination are on the same file system. You should use shutil.move instead.`

you are doing the equivalent of:
```
mv /tmp/ngrok /content/drive/RoLab/transfer_learning_tutorial/ngrok
```
right?

**Comment by mixuala** [comment]
or you can just leave it in `/tmp`, the default folder. It works fine from there, and the binary is essentially "disposable".  I think the problem is you want to copy it to `/content/drive` which may be on a different fs.
